name       : python-cloudpickle
version    : 2.2.1
release    : 12
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/refs/tags/v2.2.1.tar.gz : 63b339f3cf4d4d640a187421158148f239ec96be094726ac6bb4ba24fddb4616
homepage   : https://github.com/cloudpipe/cloudpickle
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    cloudpickle makes it possible to serialize Python constructs not supported by the default pickle module from the Python standard library.
builddeps  :
    - python-pytest-cov        # check
    - python-psutil            # check
    - python-tornado           # check
    - python-typing-extensions # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD/tests/cloudpickle_testpkg py.test3 -v -k 'not test_builtin_classmethod'
    popd
