name       : python-cloudpickle
version    : 1.5.0
release    : 5
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/v1.5.0.tar.gz : f2af00114a891731d291af3e84d6c8be1b6c6cd1d1dfcdd78c2f1c493c7cdeb4
homepage   : https://github.com/cloudpipe/cloudpickle
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    Extended pickling support for Python objects
networking : yes # Check
builddeps  :
    - pkgconfig(python3)
    - python-psutil
    - python-tox
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test tox3 -e py37
