name       : python-cloudpickle
version    : 0.5.2
release    : 2
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/v0.5.2.tar.gz : 2343a46ea5cee2925f3bd3cbd80cff1242e802463b14997a5839ca981c89db50
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    Extended pickling support for Python objects
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
