name       : python-cloudpickle
version    : 2.2.0
release    : 11
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/refs/tags/v2.2.0.tar.gz : a2c50647670f5ca9e004ce6b280c0837bc49f46a6bb6b73710238a3dcc0862cd
homepage   : https://github.com/cloudpipe/cloudpickle
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    cloudpickle makes it possible to serialize Python constructs not supported by the default pickle module from the Python standard library.
builddeps  :
    - python-pytest-cov        # check
    - python-psutil            # check
    - python-tornado           # check
    - python-typing-extensions # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD/tests/cloudpickle_testpkg py.test3 -v -k 'not test_builtin_classmethod'
    popd
