name       : python-cloudpickle
version    : 1.6.0
release    : 7
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/v1.6.0.tar.gz : a7393ad8144ecb8f4cf69f0f0a4ad15f47b7f9d0acb082b8717f1bb6a05f6de8
homepage   : https://github.com/cloudpipe/cloudpickle
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    Extended pickling support for Python objects
builddeps  :
    - pkgconfig(python3)
    - flake8
    - python-pytest
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD/tests/cloudpickle_testpkg py.test3 -v
    popd
