name       : python-cloudpickle
version    : 1.1.1
release    : 3
source     :
    - https://github.com/cloudpipe/cloudpickle/archive/v1.1.1.tar.gz : 7be223f50e0401150dbcc42d8085786c47459f2159626411b6980ccc6928f5b0
license    : BSD-3-Clause
component  : programming.python
summary    : Extended pickling support for Python objects
description: |
    Extended pickling support for Python objects
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
